run:
    sample_every: 0
    n_sample_eps: 0
    debug: false
    resume_timestamp: ''
    wandb_id: ''

logger:
    outputs: [jsonl, scope, wandb]
    wandb_filter: 'score|length|fps|train/loss/|train/rand/|report/loss/|report/openloop/|report/policy_image|eval/loss/'
    wandb_project: Lucid-Dreamer
    wandb_group: ''

env:
    vizdoom:
        skip: 4
        level: 3
        timeout: 525
        size: 64
        cheat: false
        switch_every: 1.5e6
        dy_type: 0
