vizdoom_continual:
    task: vizdoom_DeadlyCorridor
    env.vizdoom.switch_every: 1.5e6
    run:
        steps: 1e7
        train_ratio: 32
        log_every: 30
        report_every: 20000

vizdoom_fixed:
    task: vizdoom_DeadlyCorridor
    run:
        steps: 2e6
        train_ratio: 32
        log_every: 30
        report_every: 20000
        sample_every: 100000
        n_sample_eps: 25
